POST http://localhost:8000/user
Content-Type: application/json

{
  "name": "Renam Bulhões",
  "email": "renam@bulhoes.com",
  "password": "123456"
}


###

POST http://localhost:8000/user/generate_token
Content-Type: application/json

{
  "email": "renam@bulhoes.com",
  "password": "123456"
}
